#runtime: python27
#api_version: 1
#threadsafe: true
#
#handlers:
#- url: /static
#  static_dir: static
#- url: /.*
#  script: main.app

runtime: python37
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  CLOUD_STORAGE_BUCKET: YOUR_CLOUD_STORAGE_BUCKET